### ISSUE TITLE
[solved] Where can I put mongodb id/password?

### ISSUE THREAD

**Issue by online0227** [apostrophecms/apostrophe#2653]
I get following error:

```
~/apostrophe$ node app.js
Unhandled rejection MongoError: command createIndexes requires authentication
    at MessageStream.messageHandler (/home/mypc/apostrophe/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/home/mypc/apostrophe/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/mypc/apostrophe/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

Looks like it is related to mongodb auth problem since I use auth on my mongo. I searched apostrophe folder but couldn't find any config related to mongodb setup. Where is it located?

Thank you very much.

**Comment by online0227** [comment]
copy local.example.js to data/local.js after renaming, and put mongo credential info.

**Comment by online0227** [comment]
copy local.example.js to data/local.js after renaming, and put mongo credential info.

**Comment by boutell** [comment]
You can also set the APOS_MONGODB_URL environment variable.

**Comment by tuyenle-techstreet** [comment]
`APOS_MONGODB_URI` not `APOS_MONGODB_URL`

**Comment by boutell** [comment]
Correct, pardon my typo!
