### ISSUE TITLE
3.8: server error log spam for required conditional fields

### ISSUE THREAD

**Issue by myovchev** [apostrophecms/apostrophe#3569]
## To Reproduce
Create a conditional required string field. On admin UI fill without satisfying the field condition. On save everything looks good but console error `required: required` with trace is thrown.

## Expected behavior
No server error logs.

## Details
The conditional required fields were fixed not long ago. It seems the schema back-end doesn't know about that yet - here is the exact responsible code https://github.com/apostrophecms/apostrophe/blob/main/modules/%40apostrophecms/schema/index.js#L103. I have tested only `string` type,  but this might be as well the case for other types.

**Version of Node.js:** any

**Version of Apostrophe** 8.3.1

**Comment by abea** [comment]
I looked into that when I fixed the related UI bug. I agree those errors are misleading. It would require passing the full schema into each field's `convert` function. Or maybe we could check the conditional validity before that function is called, at the start of this loop's logic: https://github.com/apostrophecms/apostrophe/blob/5fc03dc0167636630ed93f9ed902185a4057bc9f/modules/%40apostrophecms/schema/index.js#L1557

**Comment by ammein** [comment]
Hey apostrophe team, I also got the same issue on getting console error `required: required` . I know this issue is opened last year but it happen on my project. This happen when I open the Modal Manager for Page. Here is server log:

```sh
POST /api/v1/@apostrophecms/notification: 

required: required
    at Object.error (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/apostrophe/modules/@apostrophecms/error/index.js:29:23)
    at Object.trigger (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/apostrophe/modules/@apostrophecms/notification/index.js:263:27)
    at post (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/apostrophe/modules/@apostrophecms/notification/index.js:119:19)
    at /Users/aminshazrin/Documents/codes/demo-a3/node_modules/apostrophe/modules/@apostrophecms/module/index.js:180:36
    at Layer.handle [as handle_request] (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/layer.js:95:5)
    at /Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/express/lib/router/index.js:280:10)
    at addGlobal (/Users/aminshazrin/Documents/codes/demo-a3/node_modules/apostrophe/modules/@apostrophecms/global/index.js:68:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by boutell** [comment]
Agreed that we should fix.
